trigger:
- master
pr:
- master
    
pool:
    vmImage: "Ubuntu 16.04"

steps:

- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.12.18'
  condition: always()
  displayName: 'Install terraform'

- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'azure_dce_nonprod'
    backendAzureRmResourceGroupName: 'apalan11apalan11-01'
    backendAzureRmStorageAccountName: 'dcetest'
    backendAzureRmContainerName: 'dcetest'
    backendAzureRmKey: $BACKEND_AZURE_RM_KEY

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/functionApp'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
