trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  LOCATION: westus
  # Uncomment & change this to something more unique before running
  # PREFIX: azuresample

jobs:
- job: SetupAzureTFBackend
  displayName: Setup TFState Azure Backend
  dependsOn: []
  steps:
  - task: AzureCLI@2
    displayName: Create resource group
    inputs:
      azureSubscription: 'azure_dce_nonprod'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az group create --name  $(PREFIX)-sample-rg --location $(LOCATION) --tags sample=azure-functions-event-grid-terraform'
  - task: AzureCLI@2
    displayName: Create tfstate storage account
    inputs:
      azureSubscription: 'azure_dce_nonprod'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az storage account create --resource-group  $(PREFIX)-sample-rg --name $(PREFIX)tfstor --kind StorageV2 --tags sample=azure-functions-event-grid-terraform'

  - task: AzureCLI@2
    displayName: Create tfstate container
    inputs:
      azureSubscription: 'azure_dce_nonprod'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az storage container create --name tfstate --account-name $(PREFIX)tfstor'